// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission8.Models;

namespace Mission8.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20230223181528_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission8.Models.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = (byte)1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = (byte)2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = (byte)3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = (byte)4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission8.Models.TaskResponse", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
